frameworkVersion: '>=1.50.0'

plugins:
  - environment-variables
  - remove-storage
  - serverless-webpack
  - content-handling
  - codebox-tools
  - set-api-host

service: jc-registry

package:
  individually: true

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${env:CODEBOX_REGION}
  environment:
    admins: ${env:CODEBOX_ADMINS}
    restrictedOrgs: ${env:CODEBOX_RESTRICTED_ORGS}
    registry: ${env:CODEBOX_REGISTRY}
    githubUrl: ${env:CODEBOX_GITHUB_URL}
    githubClientId:  ${env:CODEBOX_GITHUB_CLIENT_ID}
    githubSecret:  ${env:CODEBOX_GITHUB_SECRET}
    bucket: ${env:CODEBOX_BUCKET}-${self:provider.stage}
    region: ${self:provider.region}

    clientId: ${env:CODEBOX_INSIGHTS_CLIENT_ID}
    secret: ${env:CODEBOX_INSIGHTS_SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "sns:Publish"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.bucket}*"
        - "Fn::Join":
            - ""
            - - "arn:aws:sns:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":${self:service}-${opt:stage}-log"

functions:
  authorizerGithub:
    handler: src/authorizers/github.default

  put:
    handler: src/put/index.default
    events:
      - http:
          path: 'registry/{name}'
          method: put
          authorizer: authorizerGithub
  get:
    handler: src/get/index.default
    events:
      - http:
          path: 'registry/{name}'
          method: get
          authorizer: authorizerGithub

  distTagsGet:
    handler: src/dist-tags/get.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags'
          method: get
          authorizer: authorizerGithub
  distTagsPut:
    handler: src/dist-tags/put.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags/{tag}'
          method: put
          authorizer: authorizerGithub
  distTagsDelete:
    handler: src/dist-tags/delete.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags/{tag}'
          method: delete
          authorizer: authorizerGithub

  userPut:
    handler: src/user/put.default
    events:
      - http:
          path: 'registry/-/user/{id}'
          method: put

  userDelete:
    handler: src/user/delete.default
    events:
      - http:
          path: 'registry/-/user/token/{token}'
          method: delete
          authorizer: authorizerGithub

  whoamiGet:
    handler: src/whoami/get.default
    events:
      - http:
          path: 'registry/-/whoami'
          method: get
          authorizer: authorizerGithub

  tarGet:
    handler: src/tar/get.default
    events:
      - http:
          integration: lambda
          authorizer: authorizerGithub
          path: 'registry/{name}/-/{tar}'
          method: get
          contentHandling: CONVERT_TO_BINARY
          request:
            template:
              application/json: >
                {
                  "name": "$input.params('name')",
                  "tar": "$input.params('tar')"
                }

resources:
  Resources:
    PackageStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:provider.environment.bucket}
    PackageStoragePolicy:
      Type: "AWS::S3::BucketPolicy"
      DependsOn: "PackageStorage"
      Properties:
        Bucket:
          Ref: "PackageStorage"
        PolicyDocument:
          Statement:
            - Sid: DenyIncorrectEncryptionHeader
              Effect: Deny
              Principal: "*"
              Action: "s3:PutObject"
              Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"
              Condition:
                StringNotEquals:
                  "s3:x-amz-server-side-encryption": AES256
            - Sid: DenyUnEncryptedObjectUploads
              Effect: Deny
              Principal: "*"
              Action: "s3:PutObject"
              Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"
              Condition:
                "Null":
                  "s3:x-amz-server-side-encryption": true